

- name: Install Redis repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

- name: Enalbe Redis 6.2 repo and Install
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

- name: Update Redis listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
