#source common.sh
#
#print_head "Set up MongoDB repo"
#cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
#print_status $?
#
#print_head "Install MongoDB"
#yum install mongodb-org -y &>>${log_file}
#print_status $?
#
#print_head "Updating the mongodb listen address "
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>${log_file}
#print_status $?
#
#print_head "Enable MongoDB"
#systemctl enable mongod &>>${log_file}
#print_status $?
#
#print_head "Start MongoDB"
#systemctl restart mongod &>>${log_file}
#print_status $?

- name: SetUp MongoDB repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.buitlnin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB listen address
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB service
  ansible.builtin.systemd:
    name: mongod
    enabled: true
    state: restarted


