- name: Download Prometheus Node Exporter
  ansible.builtin.unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

- name: Copy Prometheus node exporter service fille
  ansible.builtin.template:
    src: /etc/systemd/system/node_exporter.service

- name: Start Node Exporter Service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: true
    daemon-reload: yes

