- name: Download Prometheus Node Exporter
  ansible.builtin.un_archive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

#https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz