
- name: Install Java
  ansible.builtin.yum:
    name: java-17-openjdk
    state: installed

- name: Import app-prerequisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

#- name: Installing Maven Dependencies
#  ansible.builtin.shell: mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
#  args:
#    chdir: /app

- name: Schema SetUP(If defined)
  ansible.builtin.import_tasks:
    file: schema-setup.yml
  when: schema_type is defined

- name: Load Systemd setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml