
- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Import app-prerequisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install Python Dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: Schema SetUP(If defined)
  ansible.builtin.import_tasks:
    file: schema-setup.yml
  when: schema_type is defined

- name: Load Systemd setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml