#print_head "Setup SystemD Service"
#cp ${code_dir}/configs/${component}.service /etc/systemd/system/${component}.service &>>${log_file}
#print_status $?
#
#  #setting password for payment service
#if [ ${component} == "payment" ]; then
#sed -i -e "s/ROBOSHOP_USER_PASSWORD/${roboshop_app_passwd}/" /etc/systemd/system/${component}.service &>>${log_file}
#fi
#
#  #setting password for Dispatch Service
#if [ ${component} == "dispatch" ]; then
#sed -i -e "s/ROBOSHOP_USER_PASSWD_DIS/${roboshop_app_passwd}/" /etc/systemd/system/${component}.service &>>${log_file}
#fi
#
#
#print_head " Reloading the System Background"
#systemctl daemon-reload &>>${log_file}
#print_status $?
#
#print_head "Enabling the ${component} Service"
#systemctl enable ${component} &>>${log_file}
#print_status $?
#
#print_head "Starting the ${component} Service"
#systemctl restart ${component} &>>${log_file}
#print_status $?


- name: Copy Systemd service file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Start service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: true
    daemon-reload: true