groups:
- name: roboshop-service-down-alerts
  rules:
  {% for component in components %}

  - alert: ServiceDown-Alerts - {{ component }} service
    expr: node_systemd_unit_state{exported_name="{{ component }}.service",state="active"}
    for: 30s
    labels:
      severity: critical
      appName: {{ component }}
    annotations:
      summary: Service Down on some server - service name - {{ component }}.service
  {% endfor %}


